### ISSUE TITLE
如何实现长链接发送短信？Python

### ISSUE THREAD

**Issue by dawncold** [yunpian/sms#15]

**Comment by bingone** [comment]
Hi，Thanks to v2 deploy.  now,you can send sms by yunpian-sdk-python
That is keep-alive default.
1) pip install yunpian-sdk-python
2) download and install pyDes from 
http://twhiteman.netfirms.com/pyDES/pyDes-2.0.1.zip

```
from yunpian.SmsOperator import SmsOperator
smsOperator = SmsOperator('your apikey')
result = smsOperator.single_send({'mobile': '13000000000', 'text': '【yunpian】您的验证码是4444'})
print json.dumps(result.content, ensure_ascii=False)`
```

**Comment by dawncold** [comment]
@bingone 好吧，我以为是什么神奇的技术呢
